steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}
      - --region=${_DEPLOY_REGION}
      - --platform=${_PLATFORM}
options:
  machineType: E2_HIGHCPU_32
